<?php
session_start();
include "conn.php";

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $query = strtolower(trim(htmlspecialchars($_POST["query"], ENT_QUOTES, 'UTF-8')));

    if (!empty($query)) {
        $log_stmt = $conn->prepare("INSERT INTO search_logs (query) VALUES (?)");
        $log_stmt->bind_param("s", $query);
        $log_stmt->execute();
        $log_stmt->close();
    }

    $directMatches = [
        'agency'        => 'agencies.php',
        'agencies'      => 'agencies.php',
        'bar'           => 'bars.php',
        'bars'          => 'bars.php',
        'bank'          => 'banks.php',
        'banks'         => 'banks.php',
        'bus'           => 'bus.php',
        'cafe'          => 'cafes.php',
        'cafes'         => 'cafes.php',
        'college'       => 'colleges.php',
        'colleges'      => 'colleges.php',
        'cultural'      => 'culturals.php',
        'festival'      => 'festivals.php',
        'fire'          => 'fires.php',
        'high school'   => 'highschools.php',
        'highschool'    => 'highschools.php',
        'hospital'      => 'hospitals.php',
        'hospitals'     => 'hospitals.php',
        'hotel'         => 'hotels.php',
        'hotels'        => 'hotels.php',
        'jeep'          => 'jeeps.php',
        'mall'          => 'malls.php',
        'malls'         => 'malls.php',
        'market'        => 'markets.php',
        'pharmacy'      => 'pharmacies.php',
        'plaza'         => 'plaza.php',
        'police'        => 'pnps.php',
        'resort'        => 'resorts.php',
        'restaurant'    => 'restaurants.php',
        'restaurants'   => 'restaurants.php',
        'school'        => 'highschools.php',
        'souvenir'      => 'souvenirs.php',
        'terminal'      => 'terminals.php',
        'transport'     => 'transportations.php',
        'travel agency' => 'travel_agencies.php',

        
        // direct matches
        // agencies
        'DEPED Iloilo Main Office' => 'agency1.php',
        'Department of Public Works and Highways (DPWH)' => 'agency2.php',
        'Department of Social Welfare and Development (DSWD) ' => 'agency4.php',
        'Department of Health (DOH)' => 'agency5.php',
        'Department of Agriculture (DA) ' => 'agency6.php',
        'Department of Environment and Natural Resources (DENR)' => 'agency7.php',
        'Department of Labor and Employment (DOLE)' => 'agency8.php',
        'Department of Trade and Industry (DTI)' => 'agency9.php',
        'Department of the Interior and Local Government (DILG)' => 'agency10.php',
        'Department of Tourism (DOT)' => 'agency11.php',
        'Commission on Higher Education (CHED)' => 'agency12.php',
        'Technical Education and Skills Development Authority (TESDA)' => 'agency13.php',
        'Philippine Statistics Authority (PSA)' => 'agency14.php',
        'National Economic and Development Authority (NEDA)' => 'agency15.php',
        'Bureau of Internal Revenue (BIR) ' => 'agency16.php',
        'Bureau of Customs (BOC)' => 'agency17.php',
        'Philippine Ports Authority (PPA)' => 'agency18.php',
        'Civil Service Commission (CSC)' => 'agency19.php',
        'Philippine Information Agency (PIA)' => 'agency20.php',
        'Philippine National Police (PNP) ' => 'agency21.php',
        'Bureau of Fire Protection (BFP' => 'agency22.php',
        'Philippine Coast Guard (PCG)' => 'agency23.php',
        'Land Transportation Office (LTO) ' => 'agency24.php',
        'Iloilo City Hall' => 'agency26.php',
        'Iloilo Provincial Capitol' => 'agency28.php',

        // agricultural stores
        'PANAY AGRO CENTER CORPORATION' => 'agricultural_store1.php',
        'Agro Farm Marketing' => 'agricultural_store2.php',
        'PG Poultry Supply & Variety Store' => 'agricultural_store3.php',
        'Pacifica Agrivet Supplies Inc.' => 'agricultural_store4.php',
        'MCR Agri-Venture' => 'agricultural_store5.php',
        'Agricom Visayas, Inc.' => 'agricultural_store6.php',
        'Golden Friendship Enterprises' => 'agricultural_store7.php',
        'Gito Agricultural Supply' => 'agricultural_store8.php',
        'CBA Agri-Machineries' => 'agricultural_store9.php',
        'Universal Harvester Inc.' => 'agricultural_store10.php',

        // apartments
        'One Madison Place Luxury Residences' => 'apartment1.php',
        'BDS Apartment' => 'apartment2.php',
        'LaFayette Park Square' => 'apartment3.php',
        'RJV Apartment' => 'apartment4.php',
        '22WL2 Studio Apartments' => 'apartment5.php',
        'RR&R Apartments' => 'apartment6.php',
        'The Uptown Place Condominium' => 'apartment7.php',
        'RAL APARTMENT' => 'apartment8.php',
        'SGM APARTMENTS' => 'apartment9.php',
        'Atortido Apartment/Pring-pring Apartment' => 'apartment10.php',
        'S APARTMENT & RESIDENCES' => 'apartment11.php',
        'Avida Towers Atria' => 'apartment12.php',
        'Trailer Avenue - My Apartment' => 'apartment13.php',
        'One Spatial Iloilo' => 'apartment14.php',
        'Jalandoni\'s Boarding House - Jaro Iloilo City' => 'apartment15.php',
        'CSY\'s Apartment' => 'apartment16.php',
        'Bode Apartment' => 'apartment17.php',
        'Ladores Apartment' => 'apartment18.php',
        'WV Towers 1 & 2' => 'apartment19.php',

        // bakery
        'Original Biscocho Haus' => 'bakery1.php',
        'Tibiao Bakery' => 'bakery2.php',
        'JD Bakery Cafe' => 'bakery3.php',
        'Nicolette Bakery Cafe' => 'bakery4.php',
        'Merzci' => 'bakery5.php',
        'Maiquis Bread Cakes Pastries' => 'bakery6.php',
        'BreadTalk' => 'bakery7.php',
        'Latte Coffee Cafe' => 'bakery8.php',
        'Duds Cafe' => 'bakery9.php',
        'Drip Coffee & Community' => 'bakery10.php',
        'VÈLO Bistro' => 'bakery11.php',
        'Flour Bakery + Brunch Cafe' => 'bakery12.php',
        'Palpitate Coffee ' => 'bakery13.php',
        'Neighbor Coffee' => 'bakery14.php',
        'Kai Royal Cafe' => 'cafe15.php',
        'Kurukape' => 'cafe16.php',
        'Choking Grounds Coffee' => 'cafe17.php',
        'Cafe Kuruma' => 'cafe18.php',
        'Coffee Stroll' => 'cafe19.php',
        '3rd Gen Glory\'s Cafe' => 'cafe20.php',
        'Cafe et Al' => 'cafe21.php',
        'The 60:40 Coffee' => 'cafe22.php',
        'J.CO\'s Donut and Coffee' => 'cafe23.php',
        'Starbucks' => 'cafe24.php',
        'Bluejay Coffee & Co.' => 'cafe25.php',
        '2007 Coffee and Pastries' => 'cafe26.php',


        // bank
        'bpi iloilo' => 'bank7.php',
        'bdo iloio' => 'bank9.php',
        'robinson bank' => 'bank1.php',
        'philippine national bank' => 'bank2.php',
        'union bank' => 'bank3.php',
        'metro bank' => 'bank4.php',
        'first consolidated bank' => 'bank5.php',
        'veterans bank' => 'bank6.php',
        'life bank' => 'bank8.php',
        'queenbank' => 'bank45.php',

        // bar
        'the tipsy cat' => 'bar1.php',
        'straight up rooftop bar' => 'bar2.php',
        'azul latin bistro' => 'bar3.php',
        'mo2 ice' => 'bar4.php',
        'jlk music bar' => 'bar5.php',
        'diversion 21 ktv' => 'bar6.php',
        'ill bistro' => 'bar8.php',
        'monkey business sports bar' => 'bar9.php',
        'hi-fi family ktv bar' => 'bar10.php',
        'cave super club' => 'bar11.php',
        'bull & barrel' => 'bar13.php',
        'next door private room & lounge' => 'bar14.php',
        'skyhawk resto bar' => 'bar15.php',
        'era disco & party place' => 'bar16.php',
        'bourbon street bar and grill' => 'bar17.php',
        'riffs n runs ktv bar' => 'bar18.php',
        'nctr | a cocktail bar' => 'bar19.php',
        'the versteck' => 'bar20.php',
        'drink sls' => 'bar21.php',
        'statvs: bar + lounge' => 'bar22.php',
        'go superclub and sportsbar' => 'bar24.php',
        'christie\'s' => 'bar25.php',
        'flow superclub' => 'bar26.php',
        'parple club' => 'bar27.php',
        
        // barbershops
        'PARE' => 'barbershop1.php',
        'Bruno\'s Barbers' => 'barbershop2.php',
        'Lance Barber Shop & Lean Store' => 'barbershop3.php',
        'Gent\'s Barber Iloilo Unli Haircut Always' => 'barbershop4.php',
        'Hairitage Barbershop And Salon' => 'barbershop5.php',
        'TUF Barbershop Iloilo - North Grove' => 'barbershop6.php',
        'The Fadeground Barbershop' => 'barbershop7.php',
        'Señor Barbershop' => 'barbershop8.php',
        'Kalye Barbershop' => 'barbershop9.php',
        'Hermano\'s Fade Barbershop' => 'barbershop10.php',
        'Biglang Gwapo Barbershop (The Fade Master)' => 'barbershop11.php',
        'Master Fade' => 'barbershop12.php',
        'FadeGround 2 Black Barbershop City Proper' => 'barbershop13.php',
        '4-Kizz Barbershop' => 'barbershop14.php',
        'Fadestreet Barbershop' => 'barbershop15.php',
        'Fade Xpert Jaro' => 'barbershop16.php',
        'Jems Barber Salon' => 'barbershop17.php',
        'HUNTER\'S CUT BARBER SHOP (MOLO BRANCH)' => 'barbershop18.php',
        'Auroras Cuts Barbershop' => 'barbershop19.php',
        'Bruno\'s Barbers - Festive Walk Iloilo' => 'barbershop20.php',


        // bicycle shops
        'Iloilo Bike Shop' => 'bicycle_shop1.php',
        'Alex Bike Café' => 'bicycle_shop2.php',
        'Bike Gallery Cycle Center' => 'bicycle_shop3.php',
        'Papoo Bike Shop' => 'bicycle_shop4.php',
        'DOBOL J BIKESHOP' => 'bicycle_shop5.php',
        'Robs Bikeshop & Accessories Balantang Jaro Branch' => 'bicycle_shop6.php',
        '522 Bike Shop' => 'bicycle_shop7.php',
        'MAZTA RIDE BIKE ACCESSORIES' => 'bicycle_shop8.php',
        'BGCC BIKESHOP (BIKEGALLERY)' => 'bicycle_shop9.php',
        'Planet Cycle Shoppe' => 'bicycle_shop10.php',
        'MG Bike Parts' => 'bicycle_shop11.php',
        'WELLSON CYCLE SUPPLY' => 'bicycle_shop12.php',
        'ZM Bike Parts and Accessories' => 'bicycle_shop13.php',
        'A-Bikes Enterprises' => 'bicycle_shop14.php',
        'VINSAM BIKE SHOP REPAIR & SERVICES' => 'bicycle_shop15.php',
        'Tretton' => 'bicycle_shop16.php',
        'J Unibike Parts Center' => 'bicycle_shop17.php',
        'Reen Cyce Hub' => 'bicycle_shop18.php',
        'GEA MARKETING' => 'bicycle_shop19.php',
        'HD Bicycle and Motorcycle Accessories Shop' => 'bicycle_shop20.php',

        // birth centers
        'BALBERONA FAMILY PLANNING AND MATERNITY CLINIC' => 'birth_center1.php',
        'Iloilo Fertility and Reproductive Care Center' => 'birth_center2.php',
        'CFC Birthing Center' => 'birth_center3.php',
        'La Paz Maternity & Reproductive Health Center' => 'birth_center4.php',
        'Balberona Bluestar Family Planning And Maternity Clinic' => 'birth_center5.php',
        'Pauchano Birthing Home' => 'birth_center6.php',

        // bus
        'bo. obrero - iloilo ciy proper loop' => 'bus1.php',
        'villa plaza to city proper via calumpang' => 'bus2.php',
        'ungka to city proper via cpu loop' => 'bus3.php',
        'ungka to city proper via diversion festive walk loop' => 'bus4.php',
        'festive walk to city proper via b. aquino ave. and sm city' => 'bus5.php',
        'lanit to sm city via infante' => 'bus6.php',
        'compania to city proper loop' => 'bus7.php',
        'parola to sm city via infante loop' => 'bus8.php',
        'mohon to city proper loop' => 'bus9.php',
        'buntatala / tagbak terminal to city proper loop' => 'bus10.php',
        'ticud, la paz to city proper loop' => 'bus11.php',
        'mandurriao to city proper via festive walk / b. aquino ave.' => 'bus12.php',
        'hibao-an to city proper via tabucan hub loop' => 'bus13.php',
        'hibao-an to jaro via b. aquino ave. / festive loop' => 'bus14.php',
        'molo to city proper via baluarte loop' => 'bus15.php',
        'bito-on to jaro via balabago loop' => 'bus16.php',
        'villa baybay to city proper via bonifacio' => 'bus17.php',
        'tagbak to city proper via coastal loop' => 'bus18.php',
        'bito-on to city proper via la paz loop' => 'bus19.php',
        'mohon to jaro via so oc / festive walk / isatu' => 'bus20.php',
        'tagbak / buntatala to festive walk via sm city / atria' => 'bus21.php',
        'ungka to la paz via cpu  isatu loop' => 'bus22.php',
        'mohon to mandurriao business district' => 'bus23.php',
        'la paz to festive walk via nabitasan loop' => 'bus24.php',
        'molo to city proper via general luna loop' => 'bus25.php',

        // cafe
        'bean there coffee' => 'cafe1.php',
        'local coffee hq' => 'cafe2.php',
        'monkey grounds coffee' => 'cafe3.php',
        'madge cafe' => 'cafe4.php',
        'café augusto' => 'cafe5.php',
        'coffeebreak avenue' => 'cafe6.php',
        'book latté café, library & art space' => 'cafe7.php',
        'latte coffee cafe iloilo' => 'cafe8.php',
        'duds cafe' => 'cafe9.php',
        'drip coffee & community' => 'cafe10.php',
        'velo bistro' => 'cafe11.php',
        'flour bakery' => 'cafe12.php',
        'palpitate coffee' => 'cafe13.php',
        'neighbor coffee' => 'cafe14.php',

        // call centers 
        'Concentrix Iloilo' => 'call_center1.php',
        'iQor Philippines' => 'call_center2.php',
        'TELUS Digital Philippines' => 'call_center3.php',
        'TTEC Career Hub Iloilo' => 'call_center4.php',
        'iXL SOLUTIONS PHILIPPINES' => 'call_center5.php',
        'Accentline Inc.' => 'call_center6.php',
        'TRANSCOM Iloilo' => 'call_center7.php',
        'Conectys' => 'call_center8.php',
        'Lead Generation and Donor Creation, Inc' => 'call_center9.php',
        'Savant Technologies Inc.' => 'call_center10.php',
        'OneVirtual Global Business Solutions' => 'call_center11.php',
        'MKG Bpo Services' => 'call_center12.php',
        'OneBPO' => 'call_center13.php',
        'Callbox' => 'call_center14.php',
        'Greywire Link Outsourcing' => 'call_center15.php',
        'Luxman Global Works Inc.' => 'call_center16.php',

        // car dealerships
        'BYD Iloilo' => 'car_dealership1.php',
        'Chevrolet Iloilo' => 'car_dealership2.php',
        'Foton Iloilo' => 'car_dealership3.php',
        'Geely Iloilo' => 'car_dealership4.php',
        'Honda Cars Iloilo' => 'car_dealership5.php',
        'Hyundai Iloilo' => 'car_dealership6.php',
        'Hyundai Trucks & Buses Iloilo' => 'car_dealership7.php',
        'Isuzu Iloilo Corporation' => 'car_dealership8.php',
        'MG Motor Iloilo' => 'car_dealership9.php',
        'MG Motor - SM City Branch' => 'car_dealership10.php',
        'Avescor Motors Mitsubishi Motors Iloilo' => 'car_dealership11.php',
        'Grand Canyon Iloilo - Mitsubishi Motors' => 'car_dealership12.php',
        'Iloilo Car Corporation (Nissan Iloilo)' => 'car_dealership13.php',
        'Suzuki Auto Iloilo' => 'car_dealership14.php',
        'Toyota Iloilo' => 'car_dealership15.php',

        // cars and parts
        'Iloilo Auto Supply' => 'auto_parts1.php',
        'ILOILO 3B AUTO PARTS' => 'auto_parts2.php',
        'Jupiter Auto Parts' => 'auto_parts3.php',
        'Ilas Iloilo Lucky Auto Supply, Inc.' => 'auto_parts4.php',
        'Aug Auto Parts Supply' => 'auto_parts5.php',
        'AVL AUTO SUPPLY' => 'auto_parts6.php',
        'HRN Auto Supply' => 'auto_parts7.php',
        'Radiant Auto Supply' => 'auto_parts8.php',
        'FIVE N\'ONE AUTO PARTS' => 'auto_parts9.php',
        'Narita Electrical And Auto Parts' => 'auto_parts10.php',
        'LJ Auto Supply' => 'auto_parts11.php',
        'Kobe Motor Parts Supply' => 'auto_parts12.php',
        'E & L Auto Supply' => 'auto_parts13.php',
        'Road Warriors Auto Parts & Accessories Trading' => 'auto_parts14.php',
        'JSU Auto Supply' => 'auto_parts15.php',
        'YANG2 MOTORS CO' => 'auto_parts16.php',
        'ELVIE ENTERPRISES' => 'auto_parts17.php',
        'Jiga Mags & Tire Supply' => 'auto_parts18.php',
        'PE Second Hand Parts' => 'auto_parts19.php',
        'V-cente Auto Parts' => 'auto_parts20.php',
        'Apollo Auto Supply' => 'auto_parts21.php',
        'FGN AUTO SUPPLY' => 'auto_parts22.php',
        'CENTRUM AUTOPARTS' => 'auto_parts23.php',
        'Speedzone Car Accessories' => 'auto_parts24.php',
        '76 Autoparts' => 'auto_parts25.php',
        'DC AUTOWORKZ OFF ROAD SPECIALIST AND CAR ACCESSORIES' => 'auto_parts26.php',
        'MADWheels Autoparts' => 'auto_parts27.php',
        'Kje Automotive Parts' => 'auto_parts28.php',
        'TD MARKETING' => 'auto_parts29.php',
        'Ike Auto Supply' => 'auto_parts30.php',
        'Quezon Parts Enterprises' => 'auto_parts31.php',
        'Spennergy Auto Parts Trading' => 'auto_parts32.php',
        'MLG MANUEL AUTOMOTIVE BATTERY SUPPLY' => 'auto_parts33.php',
        'CT Auto Parts Supply' => 'auto_parts34.php',
        'Five O Autoparts & General Services' => 'auto_parts35.php',
        'Rapide Auto Service' => 'auto_parts36.php',
        'Eb Autoparts Supply' => 'auto_parts37.php',
        'Lie Surplus Spare Parts' => 'auto_parts38.php',
        'F&E Autostore Jalandoni' => 'auto_parts39.php',
        'Golden Roadrunner International Corporation' => 'auto_parts40.php',
        'DM Car Accessories' => 'auto_parts41.php',
        'Red-F Auto Accessories Shop' => 'auto_parts42.php',
        'Ed Magz Auto Supply' => 'auto_parts43.php',
        'Nel Kat-Al Marketing & Auto Supply' => 'auto_parts44.php',
        'Team Bards Auto Supply' => 'auto_parts45.php',
        'Touch Up Seat Cover and Car Accessories' => 'auto_parts46.php',
        'O-Wheels Tires & Auto Supplies' => 'auto_parts47.php',
        'RES Autoparts, Inc.' => 'auto_parts48.php',
        'Ground Effects' => 'auto_parts49.php',
        'SNAPPY AUTOCARE' => 'auto_parts50.php',
        'Autoprog Automotive shop Iloilo' => 'auto_parts51.php',
        'Datatec Tornado Philippines – Iloilo' => 'auto_parts52.php',

        // churches
        'Jaro Cathedral ' => 'church1.php',
        'Molo Church (St. Anne Parish Church)' => 'church2.php',
        'Josefa L. Jara Plaza & San Jose de Placer Church (La Punta Church)' => 'church3.php',
        'St. Vincent Ferrer Seminary (Chapel)' => 'church4.php',
        'St. Clement\'s Church (Santo Niño — La Paz Church)' => 'church5.php',
        'Arevalo Parish Church (Archdiocesan Shrine of Santo Niño de Arevalo)' => 'church6.php',
        'San Jose Placer Parish Church' => 'church7.php',
        'Nstra. Sra. De La Paz Y Buen Viaje' => 'church8.php',
        'Mandurriao Church (Espousal of Our Lady Parish Church)' => 'church9.php',
        'Our Lady of Fatima Parish Church' => 'church10.php',
        'Our Lady of the Miraculous Medal Parish' => 'church11.php',
        'San José Obrero Parish Church' => 'church12.php',
        'Sta. Teresita del Niño Jesus Parish' => 'church13.php',
        'St. Clement\'s Church (Redemptorists)' => 'church14.php',
        'Victory Christian Fellowship' => 'church15.php',
        'Iloilo City Foursquare Gospel Church' => 'church16.php',
        'Grace Foursquare Gospel Church' => 'church17.php',
        'Calaparan Foursquare Gospel Church' => 'church18.php',
        'Jaro Evangelical Church, Inc.' => 'church19.php',
        'IGLESIA NI CRISTO - Iloilo City Local' => 'church20.php',
        'Iglesia Ni Cristo - Jaro Local' => 'church21.php',
        'Iglesia Ni Cristo - Mandurriao Local' => 'church22.php',
        'Iglesia Ni Cristo - La Paz Local' => 'church23.php',
        'Iglesia Ni Cristo - San Juan Local' => 'church24.php',
        'Iglesia Ni Cristo - Jibao-an Local' => 'church25.php',

        // clothing store 
        'ILLCity Clothing' => 'clothing_store1.php',
        'Uniqlo' => 'clothing_store2.php',
        'LOCALWEARBRAND' => 'clothing_store3.php',
        'Herian' => 'clothing_store4.php',
        'TAYLAY FASHION LINE' => 'clothing_store5.php',
        'Fashion Street' => 'clothing_store7.php',
        'Elsan\'s' => 'clothing_store8.php',
        'Lifestyle by Attitudes' => 'clothing_store9.php',
        'KSG Shop by Kisha' => 'clothing_store10.php',
        'ILO SCRUBS' => 'clothing_store11.php',
        'EG Trends Apparel Iloilo' => 'clothing_store12.php',
        'J&D Concept Store' => 'clothing_store13.php',
        'Anniee Apparel' => 'clothing_store14.php',
        'H&M' => 'clothing_store15.php',
        'Viscar Clothing Shop' => 'clothing_store16.php',
        'Levi\'s' => 'clothing_store17.php',
        'Nor\'s Fashion Boutique' => 'clothing_store18.php',
        'Closeouts/Export Overruns Outlet' => 'clothing_store19.php',
        'Penshoppe' => 'clothing_store20.php',
        'Once upon a child ILO' => 'clothing_store21.php',
        'Snaphack Caps & Aparrel' => 'clothing_store22.php',
        'Zoezzz Streetwear' => 'clothing_store23.php',
        'Bench' => 'clothing_store24.php',
        'Regatta' => 'clothing_store25.php',
        'Genel\'s Boutique' => 'clothing_store26.php',
        'Clothology by Liez Fashion Store' => 'clothing_store27.php',
        'Dickies' => 'clothing_store28.php',
        'Marymart Center' => 'clothing_store29.php',
        'Take the risk Merch Shop' => 'clothing_store30.php',

        // college
        'university of iloilo' => 'college1.php',
        'iloilo science and technology university' => 'college2.php',
        'st. paul university iloilo' => 'college3.php',
        'university of san agustin (USA)' => 'college4.php',
        'west visayas state university(WVSU)' => 'college5.php',
        'central philippine university (CPU)' => 'college6.php',
        'john b. lacson foundation maritime university(JBLFMU)' => 'college7.php',
        'western institute of technology (WIT)' => 'college8.php',
        'john b. lacson foundation maritime university(arevalo)' => 'college9.php',
        'iloilo doctors college (IDC)' => 'college10.php',
        'university of the philippines visayas(UPV)' => 'college11.php',
        'Cabalum Western College' => 'college12.php',
        'Colegio del Sagrado Corazon de Jesus' => 'college13.php',
        'Colegio de San Jose' => 'college14.php',

        // courier
        'J&T Express' => 'courier1.php',
        'LBC Express' => 'courier2.php',
        '2GO Express' => 'courier3.php',
        'DHL Express' => 'courier4.php',
        'Fastpak Global Express Corporation' => 'courier5.php',
        'Otranco Cargo & Logistics' => 'courier6.php',
        'Coastal Cargo Transport Services Incorporated' => 'courier7.php',
        'Jades Cargo Services, Inc.' => 'courier8.php',
        'ADSIA Logistics Iloilo' => 'courier9.php',

        // construction firms
        'F. GURREA Construction Inc.' => 'construction_firm1.php',
        'A.C. Tajanlangit Construction, Builders And Development Corporation' => 'construction_firm2.php',
        'SABRE ENGINEERING & CONSTRUCTION SERVICES' => 'construction_firm3.php',
        'ARSD CONSTRUCTION CORP.' => 'construction_firm4.php',
        'BUILDURA CONSTRUCTION SUPPLY AND SERVICES' => 'construction_firm5.php',
        'Jbhri Construction Services office' => 'construction_firm6.php',
        'Albart Builders & Construction Supply' => 'construction_firm7.php',
        'Sualyd Construction Services Corporation' => 'construction_firm8.php',
        'Paramount Industrial & Electrical' => 'construction_firm9.php',
        'JEG CONSTRUCTION FIRM CORPORATION' => 'construction_firm10.php',
        'Q.M. Florete Construction' => 'construction_firm11.php',
        'Roprim Construction Office' => 'construction_firm12.php',
        'JC Albason Builders and Supply' => 'construction_firm13.php',
        'NJS Engineering' => 'construction_firm14.php',
        'Iloilo Southprime Developers Inc' => 'construction_firm15.php',
        'R&B Corporation' => 'construction_firm16.php',
        'Domestic Construction Supply Iloilo Inc.' => 'construction_firm17.php',
        'JC Tiampong Design + Build' => 'construction_firm18.php',
        'JRBUILDERS COMPANY INC' => 'construction_firm19.php',
        'GRANDE BUILDERS AND SUPPLY' => 'construction_firm20.php',
        'Next-Gen Engineering Services' => 'construction_firm21.php',
        'AquaDyne Construction and Supply' => 'construction_firm22.php',
        '3M Construction & Development Corporation' => 'construction_firm23.php',
        'F.D. Construction and Engineering Works' => 'construction_firm24.php',
        'AGZ Builders Corporation' => 'construction_firm25.php',
        'Iloilo Builders Supply and Services' => 'construction_firm26.php',
        'Tri-Star Construction Corporation' => 'construction_firm27.php',
        'Allied Prime Builders Inc.' => 'construction_firm28.php',
        'GMB Construction & Engineering Services' => 'construction_firm29.php',
        'Villarosa Builders and Construction Supply' => 'construction_firm30.php',
        'Northbridge Engineering and Construction' => 'construction_firm31.php',
        'CEB Construction and Development' => 'construction_firm32.php',
        
        // convenience store 
        '7/11' => 'convenience_store1.php',
        'GoMart' => 'convenience_store2.php',
        'Shell Select' => 'convenience_store3.php',

        // cultural
        'museum western visayas regional museum' => 'cultural1.php',
        'museo iloilo' => 'cultural2.php',
        'museo iloilo' => 'cultural3.php',
        'museum of philippine maritime history ' => 'cultural4.php',
        'graciano lopez jaena park' => 'cultural5.php',
        'iloilo museum of contemporary art (ilomoca)' => 'cultural6.php',
        'museum of philippine economic history ' => 'cultural7.php',
        'filipino-chinese friendship arch' => 'cultural9.php',
        'villa lizares' => 'cultural11.php',
        'don joaquin ledesma ancestral house' => 'cultural12.php',


        // dialysis centers
        'R.S.I Renal Specialty Inc. Dialysis Center' => 'dialysis_center1.php',
        'CROSSWAY KIDNEY CARE INC.' => 'dialysis_center2.php',
        'The Uswag Iloilo Dialysis Center' => 'dialysis_center3.php',
        'Iloilo Uswag San Isidro Dialysis Center' => 'dialysis_center4.php',
        'R&B DIALYSIS CENTER' => 'dialysis_center5.php',
        'RSI Dialysis Center - Javellana' => 'dialysis_center6.php',
        'Medicus Healthcare Plaza Hemodialysis Center' => 'dialysis_center7.php',
        'Hartman Dialysis Center' => 'dialysis_center8.php',
        'M-3 DIALYSIS CENTER, INC.' => 'dialysis_center9.php',

        // dental clinics 
        'City Smiles Dental Clinic – Iloilo' => 'dental_clinic1.php',
        'Patiño-Sua Dental Clinic' => 'dental_clinic2.php',
        'Dimatulac Medical & Dental Clinic' => 'dental_clinic3.php',
        'My Smile Dental Care Center' => 'dental_clinic4.php',
        'iSmile Dental Clinic - Jaro' => 'dental_clinic5.php',
        'iSmile Dental Clinic - Mandurriao' => 'dental_clinic6.php',
        'High Speed Dental Clinic' => 'dental_clinic7.php',
        'Philocalist Dental Clinic' => 'dental_clinic8.php',
        'Dr.Zippy Dental Clinic' => 'dental_clinic9.php',
        'LifeSmiles Dental Care' => 'dental_clinic10.php',
        'Maxwel Dental Center' => 'dental_clinic11.php',
        'Dental Trends Iloilo (Dental Clinic)' => 'dental_clinic12.php',
        'FDC FERMINDOZA DENTAL CLINIC' => 'dental_clinic13.php',
        'Interdent Dental Clinic' => 'dental_clinic14.php',
        'Fuentes Dental Studio' => 'dental_clinic15.php',
        'Forever Smile Dental Clinic' => 'dental_clinic16.php',
        'CDent Dental Clinic' => 'dental_clinic17.php',
        'Gavieta Dental Clinic' => 'dental_clinic18.php',
        'ALTAMERA DENTAL CLINIC' => 'dental_clinic19.php',
        'Ortega Dental Clinic - Family Dentistry' => 'dental_clinic20.php',
        'Tooth World Dental Clinic by Dr. CMC Abraham' => 'dental_clinic21.php',
        'All Smiles Dental Care and Implant Center CityMall Tagbak' => 'dental_clinic22.php',
        'Villaruel Dental and Implant Center' => 'dental_clinic23.php',
        'TRI-STAR DENTAL CLINIC' => 'dental_clinic24.php',
        'Dentist Inside' => 'dental_clinic25.php',
        'Maxicare Primary Care Clinic - Iloilo' => 'dental_clinic26.php',

        // elementary
        'molo 1 elementary school' => 'elementary1.php',
        'baluarte elementary school' => 'elementary2.php',
        'rizal elementary school' => 'elementary3.php',
        'iloilo central elementary school' => 'elementary4.php',
        'la paz 1 elementary school' => 'elementary5.php',
        'molo 2 elementary school' => 'elementary6.php',
        'assumption iloilo' => 'elementary7.php',
        'angelicum school' => 'elementary8.php',
        'arevalo elementary school' => 'elementary9.php',
        'mandurriao elementary school' => 'elementary11.php',

        // fast foods
        'KFC' => 'fast_food1.php',
        'McDonald\'s' => 'fast_food2.php',
        'Jollibee' => 'fast_food3.php',
        'Chowking' => 'fast_food4.php',
        'Greenwich' => 'fast_food5.php',
        'Burger King' => 'fast_food6.php',
        'Mang Inasal' => 'fast_food7.php',
        'Andok\'s' => 'fast_food8.php',
        'Yellow Cab' => 'fast_food9.php',
        'Pizza Hut' => 'fast_food10.php',
        'Shakey\'s' => 'fast_food11.php',
        'Tokyo Tokyo' => 'fast_food12.php',

        // ferry
        '2GO' => 'ferry1.php', 

        // fires
        'jaro fire sub station' => 'fire2.php',
        'molo fire station' => 'fire3.php',
        'arevalo fire sub-station' => 'fire4.php',
        'Alta Tierra Village Fire Sub-Station' => 'fire5.php',
        'Mandurriao Fire Sub Station' => 'fire6.php',
        'Federation Iloilo Fire Brigade Incorporated' => 'fire7.php',
        'Ungka Fire Sub-Station' => 'fire8.php',
        'Bureau of Fire Protection RHQ 6' => 'fire9.php',
        'BO.OBRERO FIRE SUB-STATION' => 'fire10.php',
        'Tagbak Fire Sub-Station' => 'fire11.php',
        'Sto. Niño Sur Fire Sub-Station' => 'fire12.php',

        // flower shops
        'acostas flowershop' => 'flowershop1.php',
        'maria flower shop' => 'flowershop2.php',
        'flos libido flower shop' => 'flowershop3.php',
        'flowers by richard' => 'flowershop4.php',
        'flower express' => 'flowershop6.php',

        // food
        'robertos' => 'food2.php',
        'tatoys manokan and seafoods' => 'food3.php',
        'pancit molo' => 'food4.php',
        'breakthrough restaurant' => 'food7.php',
        'barquillos' => 'food8.php',
        'Bettys Ilonggo Table and Bakehouse' => 'food9.php',
        'Ilonggo Pitmaster' => 'food10.php',
        'Batchoy ilonggo foodhaus' => 'food11.php',
        'Pigadong Sosyal Nilagaan & Restobar' => 'food12.php',
        'Balai ilonggo' => 'food13.php',
        'PUNOT' => 'food14.php',
        'Ang Kamalig Restaurant' => 'food15.php',
        'Netongs Original Special La Paz Batchoy' => 'food16.php',
        'Ted_s Oldtimer Lapaz Batchoy' => 'food17.php',
        'Camina - Camiña Balay nga Bato' => 'food18.php',
        'Deco_s Original La Paz Batchoy (Lapaz)' => 'food19.php',
        'Marcela Chicken Inasal & Salty Beach Bar' => 'food20.php',
        'Fusion Beach Restaurant & Shisha Bar Calaparan' => 'food21.php',
        'Lunas Arrozcaldohan' => 'food22.php',
        'Popoys Batchoy' => 'food23.php',
        'ocean city seafood and restaurants, inc' => 'food24.php',
        'ponsyon by breakthrough' => 'food25.php',
        'seven fishes by coco veranda' => 'food26.php',
        'dapli restaurant' => 'food27.php',
        'the promenade' => 'food28.php',

        // funeral services
        'Forest Lake Memorial Parks' => 'funeral_service1.php',
        'Gegato Abecia Funeral Homes Inc & Crematory' => 'funeral_service2.php',
        'Saint Therese Memorial Chapel, Inc.' => 'funeral_service3.php',
        'Cosmopolitan-Somo Memorial Homes' => 'funeral_service4.php',
        'St. Peter Chapels (Mega) - Iloilo' => 'funeral_service5.php',

                // gas stations
        'Petron' => 'gas_station1.php',
        'Shell' => 'gas_station2.php',
        'Caltex' => 'gas_station3.php',
        'Total' => 'gas_station4.php',
        'Seaoil' => 'gas_station5.php',
        'Phoenix' => 'gas_station6.php',
        'Jetti' => 'gas_station7.php',

        // gyms
        'Blackout Fitness Iloilo' => 'gym1.php',
        'Anytime Fitness Iloilo' => 'gym2.php',
        'Gold\'s Gym Iloilo' => 'gym3.php',
        'X-Fit Gym formerly Mefit Gym' => 'gym4.php',
        'The Ultimate Fitness Gym' => 'gym5.php',
        'Housefit Gym' => 'gym6.php',
        'TEN122 Athletics | Premium Fitness Gym' => 'gym7.php',
        'Ironforge Fitness Center' => 'gym8.php',
        'Sports and Fitness Center Iloilo' => 'gym9.php',
        'Prime Fitness Gym' => 'gym10.php',

        // hardware
        'Far Eastern Hardware' => 'hardware1.php',
        'ACE Hardware' => 'hardware2.php',
        'Citi Hardware' => 'hardware3.php',
        'Wilcon Depot' => 'hardware4.php',
        'Northern Iloilo Lumber and Hardware' => 'hardware5.php',
        'South Pacific Builders Center' => 'hardware6.php',
        'Iloilo Central Lumber' => 'hardware7.php',
        'Dezine Builders Depot' => 'hardware8.php',
        'Handyman' => 'hardware9.php',
        'Iloilo MTG Hardware' => 'hardware10.php',
        'CTLS Hardware' => 'hardware11.php',
        'Super Agro Machinery and Hardware Corp.' => 'hardware12.php',
        'Iloilo City Hardware' => 'hardware13.php',
        'Iloilo Central Hardware' => 'hardware14.php',
        'S & C Hardware' => 'hardware15.php',
        'SGB Hardware' => 'hardware16.php',
        'Northern Iloilo Lumber and Hardware' => 'hardware17.php',
        'Asian Lumber & Hardware Inc' => 'hardware18.php',
        'GER-B MARKETING' => 'hardware19.php',
        'Jimmy\'s Hardware' => 'hardware20.php',
        'Metro Pacific Construction Supply, Inc.' => 'hardware21.php',
        'Jocson Hardware & Construction Supply' => 'hardware22.php',

        // highschools
        'central philippine university senior high school' => 'highschool1.php',
        'iloilo city national high school' => 'highschool2.php',
        'iloilo national high school' => 'highschool3.php',
        'jaro national high school' => 'highschool4.php',
        'philippine science high school western visayas campus' => 'highschool5.php',
        'mandurriao national high school' => 'highschool6.php',
        'iloilo sun yat sen high school' => 'highschool7.php',
        'jalandoni memorial national high school' => 'highschool8.php',
        'ramon avanceña national high school' => 'highschool9.php',
        'hua siong college of iloilo main campus' => 'highschool10.php',
        'university of san agustin-hs campus' => 'highschool11.php',
        'la paz national high school' => 'highschool12.php',
        'phinma university of iloilo' => 'highschool13.php',

        // home stores
        'OUR HOME' => 'home_store1.php',
        'Iloilo Home Art Furniture' => 'home_store2.php',
        'Iloilo RGB Home Furniture' => 'home_store3.php',
        'Mandaue Foam' => 'home_store4.php',
        'Elegant Solid Wood Furniture' => 'home_store5.php',
        'MoostBrand Home Depot' => 'home_store6.php',
        'UNITOP' => 'home_store7.php',
        'Wilcon Depot' => 'home_store8.php',
        'Furniture Trends by Shadrea Co.' => 'home_store9.php',
        'Cathy Home Furniture' => 'home_store10.php',
        'MOOSTBRAND' => 'home_store11.php',
        'Triumph Home Depot' => 'home_store12.php',
        'Progress Home and Office Furnishings' => 'home_store13.php',
        'Japan Home Centre - Festive Walk' => 'home_store14.php',
        'Furniture Republic' => 'home_store15.php',
        'Solidgold Multi Resources Corp.' => 'home_store16.php',
        'Asian Home' => 'home_store17.php',
        'Longwin' => 'home_store19.php',
        'Light Me Up' => 'home_store20.php',
        'Domo-Domo Japan Surplus' => 'home_store21.php',
        'STONE DEPOT | Granite Marble Quartz' => 'home_store22.php',
        'Miniso' => 'home_store23.php',
        'YM Building, North-East Home Depot' => 'home_store26.php',
        'Floor Center Ilo-ilo' => 'home_store27.php',

        // historicals
        'molo church' => 'historical6.php',
        'avancena anscestral house' => 'historical8.php',
        'calle real' => 'historical13.php',
        'casa mariquit' => 'historical10.php',
        'casa real' => 'historical5.php',
        'jaro cathedral' => 'historical7.php',
        'molo mansion' => 'historical1.php',
        'nelly garden' => 'historical2.php',
        'old iloilo city hall' => 'historical4.php',
        'plaza libertad' => 'historical9.php',
        'rosendo mejica' => 'historical3.php',

        // hospitals
        'iloilo mission hospital' => 'hospital1.php',
        'st. paul\'s hospital of iloilo, inc.' => 'hospital2.php',
        'healthway qualimed hospital iloilo' => 'hospital3.php',
        'the medical city iloilo' => 'hospital4.php',
        'iloilo doctors\' hospital, inc.' => 'hospital5.php',
        'medicus medical center' => 'hospital6.php',
        'western visayas medical center' => 'hospital7.php',
        'metro iloilo hospital and medical center, inc.' => 'hospital8.php',
        'asia pacific medical center' => 'hospital9.php',
        'west visayas state university medical center' => 'hospital10.php',
        'amosup seamen\'s hospital iloilo' => 'hospital11.php',
        'supercare iloilo' => 'hospital12.php',
        'health metrics inc.' => 'hospital13.php',

        // hotels
        'richmonde hotel' => 'hotel1.php',
        'park inn radisson' => 'hotel2.php',
        'grand xing imperial hotel' => 'hotel3.php',
        'diversion 21 hotel' => 'hotel4.php',
        'zuri hotel' => 'hotel5.php',
        'seda atria hotel' => 'hotel6.php',
        'injap tower hotel' => 'hotel7.php',
        'go hotel' => 'hotel8.php',
        'courtyard hotel' => 'hotel9.php',
        'citadine amigo hotel' => 'hotel10.php',
        'harbor town hotel' => 'hotel14.php',
        'highway 21 hotel' => 'hotel15.php',
        'hotel del rio' => 'hotel16.php',
        'j7 hotel' => 'hotel17.php',
        'smallville 21 hotel' => 'hotel18.php',
        'century 21 hotel' => 'hotel19.php',
        'days hotel iloilo' => 'hotel20.php',
        'goldberry lite hotel' => 'hotel21.php',

        // internet services
        'PLDT' => 'internet_services1.php',
        'Globe Telecom Inc Store SM City Iloilo' => 'internet_services2.php',
        'Converge' => 'internet_services3.php',
        'SkyConvergence, Inc.' => 'internet_services4.php',


        // jeeps
        'ROUTE 1: BO. OBRERO, LAPUZ TO CITY PROPER LOOP' => 'jeep1.php',
        'ROUTE 2: VILLA PLAZA TO CITY PROPER VIA CALUMPANG' => 'jeep2.php',
        'ROUTE 3: UNGKA TO CITY PROPER VIA CPU LOOP' => 'jeep3.php',
        'ROUTE 4: UNGKA TO CITY PROPER VIA B. AQUINO AVE./ FESTIVE WALK LOOP' => 'jeep4.php',
        'ROUTE 5: FESTIVE WALK TO CITY PROPER VIA B. AQUINO AVE. AND SM CITY' => 'jeep5.php',
        'ROUTE 6: LANIT TO SM CITY VIA INFANTE' => 'jeep6.php',
        'ROUTE 7: COMPANIA TO CITY PROPER LOOP' => 'jeep7.php',
        'ROUTE 8: PAROLA TO SM CITY VIA INFANTE LOOP' => 'jeep8.php',
        'ROUTE 9: MOHON TO CITY PROPER LOOP' => 'jeep9.php',
        'ROUTE 10: BUNTATALA / TAGBAK TERMINAL TO CITY PROPER LOOP' => 'jeep10.php',
        'ROUTE 11: TICUD, LA PAZ TO CITY PROPER LOOP' => 'jeep11.php',
        'ROUTE 12: MANDURRIAO TO CITY PROPER VIA FESTIVE WALK / B. AQUINO AVE.' => 'jeep12.php',
        'ROUTE 13: HIBAO-AN TO CITY PROPER VIA TABUCAN HUB LOOP' => 'jeep13.php',
        'ROUTE 14: HIBAO-AN TO JARO VIA B. AQUINO AVE. / FESTIVE LOOP' => 'jeep14.php',
        'ROUTE 15: MOLO TO CITY PROPER VIA BALUARTE LOOP' => 'jeep15.php',
        'ROUTE 16: BITO-ON TO JARO VIA BALABAGO LOOP' => 'jeep16.php',
        'ROUTE 17: VILLA BAYBAY TO CITY PROPER VIA BONIFACIO' => 'jeep17.php',
        'ROUTE 18: TAGBAK TO CITY PROPER VIA COASTAL LOOP' => 'jeep18.php',
        'ROUTE 19: BITO-ON TO CITY PROPER VIA LA PAZ LOOP' => 'jeep19.php',
        'ROUTE 20: MOHON TO JARO VIA SO OC / FESTIVE WALK / ISATU' => 'jeep20.php',
        'ROUTE 21: TAGBAK / BUNTATALA TO FESTIVE WALK VIA SM CITY / ATRIA' => 'jeep21.php',
        'ROUTE 22: UNGKA TO LA PAZ VIA CPU – ISATU LOOP' => 'jeep22.php',
        'ROUTE 23: MOHON TO MANDURRIAO BUSINESS DISTRICT' => 'jeep23.php',
        'ROUTE 24: LA PAZ TO FESTIVE WALK VIA NABITASAN LOOP' => 'jeep24.php',
        'ROUTE 25: MOLO TO CITY PROPER VIA GENERAL LUNA LOOP' => 'jeep25.php',


        // laundry
        'New Laundry King' => 'laundry1.php',
        'Misis Clean Laundromat' => 'laundry2.php',
        'TAFT LOUNGE LAUNDROMAT' => 'laundry4.php',
        'Laundry Lab Express Washhouse' => 'laundry5.php',
        'Mr. Labada' => 'laundry6.php',

        // markets
        'iloilo central market' => 'market1.php',
        'iloilo terminal market' => 'market2.php',
        'la paz public market' => 'market3.php',
        'jaro public market' => 'market4.php',
        'arevalo public market' => 'market5.php',
        'mandurriao public market' => 'market6.php',
        
        // malls
        'festive walk mall' => 'mall26.php',
        'robinsons place iloilo' => 'mall27.php',
        'atrium mall' => 'mall28.php',
        'sm city iloilo' => 'mall29.php',
        'marymart center' => 'mall30.php',
        'citymall parola' => 'mall31.php',
        '1688 mall' => 'mall32.php',
        'city time square' => 'mall33.php',
        'icc gaisano' => 'mall34.php',
        'plazuela de iloilo' => 'mall35.php',
        'robinsons place jaro' => 'mall36.php',
        'galleria iloilo' => 'mall37.php',
        'gt mall molo' => 'mall38.php',
        'gaisano capital lapaz' => 'mall39.php',
        'citymall tagbak' => 'mall40.php',
        'sm delgado' => 'mall41.php',
        's&r membership shopping' => 'mall42.php',

        // meat shops
        'Iloilo City Halal Meat Shop' => 'meat_shop1.php',
        'The Pork Shop' => 'meat_shop2.php',
        'Edwin Reyes Meat Shop' => 'meat_shop3.php',
        'Ersi Meat Products Wholesaler/Retailer' => 'meat_shop4.php',
        'EFM Meatshop' => 'meat_shop5.php',
        'Chelton Steaks Iloilo' => 'meat_shop6.php',
        'Pork Shop Faith Farms' => 'meat_shop7.php',
        'Jose Alexis Rojo Meat Shops & Vegies' => 'meat_shop8.php',
        'Graciana\'s Fresh Cuts' => 'meat_shop9.php',
        'CARES MEAT FOODS, INC.' => 'meat_shop10.php',

        // medical diagnostic clinics
        'Plaza Libertad Medical Specialists’ Center' => 'medical_diagnostic_clinic1.php',
        'Medicus Diagnostic Center- Main' => 'medical_diagnostic_clinic2.php',
        'Medicus Diagnostic Center- Jaro' => 'medical_diagnostic_clinic3.php',
        'Medicus Diagnostic Center- La Paz' => 'medical_diagnostic_clinic4.php',
        'Medicus Diagnostic Center- Molo' => 'medical_diagnostic_clinic5.php',
        'Medicus Diagnostic Center - Plaza Libertad' => 'medical_diagnostic_clinic6.php',
        'Healthlink' => 'medical_diagnostic_clinic7.php',
        'Family Diagnostic Center' => 'medical_diagnostic_clinic8.php',
        'ILOILO PDS AND LABORATORY CENTER' => 'medical_diagnostic_clinic9.php',
        'Philippine Red Cross Iloilo Chapter' => 'medical_diagnostic_clinic10.php',
        'Biofera Medical Diagnostic Center' => 'medical_diagnostic_clinic11.php',
        'ML Diagnostic Center' => 'medical_diagnostic_clinic12.php',
        'TRANSNATIONAL MEDICAL & DIAGNOSTIC CENTER, INC.' => 'medical_diagnostic_clinic13.php',
        'Aqueheart Medical Diagnostic Center' => 'medical_diagnostic_clinic14.php',
        'Statlab Medical And Diagnostic Center' => 'medical_diagnostic_clinic15.php',
        'Dr. V.T. Taleon Medical Clinic X-Ray and Diagnostic Laboratory' => 'medical_diagnostic_clinic16.php',
        'ZSO DIAGNOSTICS AND LABORATORIES' => 'medical_diagnostic_clinic18.php',
        'Confluence Medical Laboratory and Diagnostic Center' => 'medical_diagnostic_clinic19.php',
        'Medisense Laboratory Center Inc.' => 'medical_diagnostic_clinic20.php',
        'Iloilo Diagnostic Ultra Sound Center' => 'medical_diagnostic_clinic21.php',
        'Ultracare Diagnostic Center, Inc.' => 'medical_diagnostic_clinic22.php',
        'Best Care Specialty Clinic and Diagnostic Center, Incorporated' => 'medical_diagnostic_clinic23.php',
        'Singapore Diagnostics - Laboratory Testing & Blood Tests' => 'medical_diagnostic_clinic25.php',
        'Health Metrics Inc.' => 'medical_diagnostic_clinic26.php',
        'MD PALMES (PERPETUAL HELP) ULTRASOUND AND DIAGNOSTIC CENTER' => 'medical_diagnostic_clinic27.php',
        'Bioshield Family Clinic And Diagnostic Center' => 'medical_diagnostic_clinic28.php',
        'GCJ DIAGNOSTIC CENTER' => 'medical_diagnostic_clinic29.php',
        'HEALTH CHECK DIAGNOSTIC LABORATORY' => 'medical_diagnostic_clinic30.php',
        'Primeview' => 'medical_diagnostic_clinic32.php',
        'RN Medical Laboratory' => 'medical_diagnostic_clinic33.php',
        'Demic Lab' => 'medical_diagnostic_clinic34.php',
        'Medical Imaging Clinic' => 'medical_diagnostic_clinic35.php',
        'Apex Primed Diagnostics, Clinics & Pharmacy' => 'medical_diagnostic_clinic36.php',
        'Healthscreen Clinical Laboratory co.' => 'medical_diagnostic_clinic37.php',
        'WVSUMC Molecular Diagnostic Laboratory' => 'medical_diagnostic_clinic38.php',

        // motorcycle shops
        'Solid Motorcycle Distributors, Inc.' => 'motorcycle_shop1.php',
        'Guanzon' => 'motorcycle_shop2.php',
        'Du Ek Sam, Inc.' => 'motorcycle_shop3.php',
        'MotorcycleCity Iloilo' => 'motorcycle_shop4.php',
        'Solid Motorcycle Distributors, Inc.' => 'motorcycle_shop5.php',
        'Suerte Motoplaza' => 'motorcycle_shop6.php',
        'Motortrade - Delgado' => 'motorcycle_shop7.php',
        'Iloilo Buantong Enterprises' => 'motorcycle_shop8.php',
        'DES MARKETING, INC.' => 'motorcycle_shop9.php',
        'Suzuki Delgado, Iloilo City - SMDI 3S Shop' => 'motorcycle_shop10.php',
        'Premio Iloilo Multi' => 'motorcycle_shop11.php',
        'Ropali' => 'motorcycle_shop12.php',
        'Wheeltek' => 'motorcycle_shop13.php',
        'Premiumbikes Jaro Iloilo' => 'motorcycle_shop14.php',
        'Yamaha Revzone - Des Strong' => 'motorcycle_shop15.php',
        'Yamaha 3S Shop - Des Marketing' => 'motorcycle_shop16.php',
        'Yamaha 3S Shop - UEMI' => 'motorcycle_shop17.php',
        'Suzuki Jaro - SMDI 3s Shop' => 'motorcycle_shop18.php',
        'KTM' => 'motorcycle_shop19.php',
        'RUSI' => 'motorcycle_shop20.php',
        'Motorstar' => 'motorcycle_shop21.php',

        // new tourist spots
        'iloilo river esplanade'  => 'new_tourist_spot1.php',
        'sunset boulevard'  => 'new_tourist_spot2.php',
        'Iloilo Business Park'  => 'new_tourist_spot3.php',

        //  optical clinics
        'Sunnies Specs Optical' => 'optical_clinic1.php',
        'Sunnies Studios' => 'optical_clinic2.php',
        'EO Executive Optical - SM City Iloilo' => 'optical_clinic3.php',
        'EO Executive Optical - Robinsons Iloilo' => 'optical_clinic4.php',
        'EO Executive Optical - Festive Walk Iloilo' => 'optical_clinic5.php',
        'EO - Executive Optical Robinsons Jaro' => 'optical_clinic6.php',
        'Ideal Vision Center' => 'optical_clinic7.php',
        'Ideal Vision - Robinsons Jaro' => 'optical_clinic8.php',
        'Owndays' => 'optical_clinic9.php',
        'Sarabia Optical' => 'optical_clinic10.php',
        'The Eye City' => 'optical_clinic11.php',
        'The Eye City - Iloilo Festive Walk Mall' => 'optical_clinic12.php',
        'Chavoso-Cabangal Optical Clinic' => 'optical_clinic13.php',
        'Vision Express - Festive Walk Iloilo' => 'optical_clinic14.php',
        'Pesongco-Flores Optical Clinic' => 'optical_clinic15.php',
        'Gorriceta Eye Clinic' => 'optical_clinic16.php',

        // pawnshops
        'Palawan Pawnshop' => 'pawnshop1.php',
        'M Lhuillier' => 'pawnshop2.php',
        'Cebuana Lhuillier' => 'pawnshop3.php',
        'RD Pawnshop' => 'pawnshop4.php',
        'Sarabia Pawnshop and Jewelry' => 'pawnshop5.php',

        // plaza
        'molo plaza' => 'plaza1.php',
        'plaza libertad' => 'plaza2.php',
        'jaro plaza' => 'plaza3.php',
        'plaza mandurriao' => 'plaza4.php',
        'plaza la paz' => 'plaza5.php',
        'villa arevalo district plaza' => 'plaza6.php',

        // pharmacy
        'rose pharmacy' => 'pharmacy1.php',
        'mercury drug store' => 'pharmacy2.php',
        'watsons' => 'pharmacy3.php',
        'CziCza Drugstore and Medical Clinic' => 'pharmacy4.php',
        'Jasac Drugstore' => 'pharmacy5.php',
        'JOSMEF PHARMA INC' => 'pharmacy6.php',
        'R&R Drugstore' => 'pharmacy7.php',
        'Sens Mieux Drug And Medical Supplies' => 'pharmacy8.php',
        'Asclepius Drug Store' => 'pharmacy9.php',
        'Generika Drugstore' => 'pharmacy10.php',
        'Guimhealth Pharmaceutical Distributor and Drugstore' => 'pharmacy11.php',
        'GoHealth Plus Pharmacy' => 'pharmacy12.php',
        "ERIN'S Family Pharmacy" => 'pharmacy13.php',
        'Iloilo Grace Pharmacy' => 'pharmacy14.php',
        'Bunda Pharmacy' => 'pharmacy15.php',
        'THE GENERICS PHARMACY' => 'pharmacy16.php',
        'Super Value Pharmacy' => 'pharmacy17.php',
        'IS Medicine' => 'pharmacy18.php',
        "L' Ca Chris Pharmacy" => 'pharmacy19.php',
        'Glory Pharmacy' => 'pharmacy20.php',
        'SOUTHSTAR DRUG' => 'pharmacy21.php',
        'JGC PHARMACY' => 'pharmacy22.php',
        'LIFE EXTENSION Medical Clinic, Pharmacy, & Laboratory Center' => 'pharmacy23.php',
        'IDJ Pharmacy' => 'pharmacy24.php',
        'Ava Kris Pharmacy And Tradelines' => 'pharmacy25.php',
        'Ledi Pharmacy' => 'pharmacy26.php',
        'MEDPHAR DRUGSTORE' => 'pharmacy27.php',
        'Rx Med Pharmacy' => 'pharmacy28.php',
        'La PharmaCera Drugstore' => 'pharmacy29.php',
        'E. Berlin Pharmacy' => 'pharmacy30.php',
        'Health Pharmacare' => 'pharmacy31.php',
        'Apex Primed Diagnostics, Clinics & Pharmacy' => 'pharmacy32.php',
        'HERVAS CARE PHARMACY' => 'pharmacy33.php',
        'Bienz Pharmacy' => 'pharmacy34.php',


        // pnp
        'philippine national police region vi' => 'pnp1.php',
        'molo district police station' => 'pnp2.php',
        'iloilo city police station 3' => 'pnp3.php',
        'police station 2 lapaz' => 'pnp4.php',
        'community police assistance center (lapaz substation)' => 'pnp5.php',
        'Mandurriao Police Station' => 'pnp6.php',
        'ILOILO CITY POLICE STATION 5' => 'pnp7.php',
        'iloilo city police station 8' => 'pnp9.php',
        'ICPO Police Station 9' => 'pnp10.php',
        'Iloilo City Police Station 7' => 'pnp11.php',
        'Arevalo Police Station' => 'pnp12.php',
        'Philippine National Police - RD PRO 6' => 'pnp13.php',

        // printing services 
        'FISHERMAN PRINT SERVICES' => 'printing_services1.php',
        'PANAY BULLETIN' => 'printing_services2.php',
        'Iloilo Printing Services' => 'printing_services3.php',
        'Multi-Print Printing & Supply' => 'printing_services4.php',
        'Hometown Printing Press' => 'printing_services5.php',
        'Iloilo Printing Haus' => 'printing_services6.php',
        'New Generation B-Art Tarpaulin Printing Services' => 'printing_services7.php',
        'Jeric Dave Copy Center (Magdalo)' => 'printing_services8.php',
        'Jeric Dave Copy Center (West Branch)' => 'printing_services9.php',
        'Print&Signs.ph' => 'printing_services10.php',
        'Maratas Printing Press' => 'printing_services11.php',
        'GM PRINTS ILOILO' => 'printing_services12.php',
        'M. Cloud Printing' => 'printing_services13.php',
        'Print Saver - Iloilo' => 'printing_services14.php',
        'Transfer It Iloilo' => 'printing_services15.php',
        'Kadesignz Innovative Printing Services' => 'printing_services16.php',

        // restaurants
        'waterfront seafood & cocktails' => 'restaurant1.php',
        'teds lapaz batchoy' => 'restaurant2.php',
        'robertos' => 'restaurant3.php',
        'tatoys manokan and seafoods' => 'restaurant4.php',
        'giuseppe iloilo' => 'restaurant5.php',
        'seoul mate home kitchen' => 'restaurant6.php',

        // resorts
        'iloilo paraw beach resort' => 'resort1.php',
        'sea garden resort' => 'resort3.php',
        'fredman beach resort' => 'resort4.php',
        'punta villa resort inc' => 'resort5.php',
        'villa rosa by the sea' => 'resort6.php',

        // review centers
        'study now review center' => 'review_center1.php',
        'ear math & science review & tutorial center' => 'review_center2.php',
        'qr training center (quality review)' => 'review_center3.php',
        'istep-up juku review & tutorial center' => 'review_center4.php',
        'padilla review center iloilo' => 'review_center5.php',
        'concept engineering review and training center' => 'review_center6.php',
        'mind point review and training center' => 'review_center7.php',
        'imath review and tutorial hub' => 'review_center8.php',
        'datsmile review and tutorial center' => 'review_center9.php',
        'amici review center iloilo' => 'review_center10.php',
        'pcce review center' => 'review_center11.php',
        'gold rank review center iloilo' => 'review_center12.php',
        'uno review and tutorial center' => 'review_center13.php',
        'toprank review academy - iloilo branch' => 'review_center14.php',
        'noelles review center incorporated' => 'review_center15.php',
        'brightmate tutorial center' => 'review_center16.php',
        'atlas iloilo - online maritime review center for marine deck & engine officers' => 'review_center17.php',
        'score high english proficiency center' => 'review_center18.php',

        // salons
        'gemien fix salon' => 'salon1.php',
        'studio 28 hair salon' => 'salon2.php',
        'city salon & spa' => 'salon3.php',
        'bangs tony & jackey korean salon' => 'salon4.php',
        'shine korean salon' => 'salon5.php',

        // samgyupsal restaurants
        'Gamcheon Korean BBQ' => 'samgyupsal_restaurant1.php',
        '2D SAMGYUP SARANGHAE' => 'samgyupsal_restaurant2.php',
        'Romantic Baboy' => 'samgyupsal_restaurant3.php',
        'Samgyeopmasarap' => 'samgyupsal_restaurant4.php',
        'Premier the Samgyupsal' => 'samgyupsal_restaurant5.php',
        'Maria Gracias Samgyupsal' => 'samgyupsal_restaurant6.php',


        // souvenirs
        'vinru d\'s shop' => 'souvenir1.php',
        'tinukib pasalubong center' => 'souvenir2.php',
        'lea and bon native products & souvenirs' => 'souvenir3.php',
        'carries gift shop' => 'souvenir4.php',
        'zizza\'s shop prints, craft and souvenirs' => 'souvenir5.php',
        'kultura filipino - iloilo, the sm store' => 'souvenir6.php',
        'yelsticker shop' => 'souvenir7.php',
        'k&h souvenir & printing services' => 'souvenir8.php',

        // study hub
         'meliora co-working & learning hub' => 'study_hub1.php',
        'homework study hub' => 'study_hub2.php',
        'ws students & professionals lounge' => 'study_hub3.php',
        'dayon co-working space' => 'study_hub4.php',
        'dnd co-working space' => 'study_hub5.php',
        'minds crib  study hub & co-working space' => 'study_hub6.php',
        'hifive - coworking space iloilo' => 'study_hub7.php',
        'space sanity study hub & coworking space' => 'study_hub8.php',
        'ubra (shared space + study hub)' => 'study_hub9.php',
        'warden station study hub · food ·coffee' => 'study_hub10.php',
        'hubworx' => 'study_hub11.php',
        'study cube' => 'study_hub12.php',
        'túon co-working space - molo branch' => 'study_hub13.php',
        'grindrz hub' => 'study_hub14.php',
        'eco-hub co-working space' => 'study_hub15.php',
        'túon cpu coworking space' => 'study_hub16.php',
        ' CoLab Coworking Space' => 'study_hub17.php',

        // terminals
        'ticud terminal' => 'terminal1.php',
        'aleosan transport terminal' => 'terminal2.php',
        'festive walk transport hub' => 'terminal3.php',
        'ceres northbound terminal' => 'terminal4.php',
        'tagbak terminal' => 'terminal5.php',
        'iloilo central line bus & jeepney terminal' => 'terminal6.php',
        'iloilo fastcraft & roro - terminal' => 'terminal7.php',
        'ceres bus terminal in mohon' => 'terminal8.php',
        'iloilo ferry terminal-parola' => 'terminal9.php',
        'ungka jeep terminal' => 'terminal11.php',
        'mohon terminal' => 'terminal12.php',

        // travel agency
        'Iloilo Skyways Travel & Tours' => 'travel_agency1.php',
        'Tickets to Go' => 'travel_agency4.php',
        'Highly Yellowstone Travel and Tours' => 'travel_agency5.php',
        '3 Wills Travel and Tours Educational Services' => 'travel_agency6.php',
        'Allstar Travel and Events Co.' => 'travel_agency8.php',
        'Buenas Grande Travel and Tours' => 'travel_agency9.php',
        'Constellation Travels, Inc.' => 'travel_agency10.php',
        'ELS Travel & Tours' => 'travel_agency11.php',
        'Eon Travel & Tours' => 'travel_agency12.php',
        'Getaway Travel and Tours' => 'travel_agency13.php',
        'Gidcel’s Travel and Tours Inc.' => 'travel_agency14.php',
        'Happy Cola Travel Consultancy and Leisure Development Corporation' => 'travel_agency17.php',
        'IExplore Travels Unlimited Co.' => 'travel_agency18.php',
        'Island Adventure Tours and Travel' => 'travel_agency19.php',
        'LAL Smallville Travel & Tours' => 'travel_agency21.php',
        'Paradise World Travel and Tours' => 'travel_agency24.php',
        'Partners Travel & Tours' => 'travel_agency25.php',
        'Racso Air Travel & Tours, Inc.' => 'travel_agency26.php',
        'Rexsengen Vee Travel & Tours, Inc.' => 'travel_agency27.php',
        'Southwest Tours (Boracay) Inc.' => 'travel_agency29.php',
        'Travel & Marketing Experts Corp.' => 'travel_agency31.php',
        'Trimeridian Travels' => 'travel_agency32.php',

        // travel ticketing
        'Tickets To Go!' => 'travel_ticketing1.php',
        'Rakso Air Travel & Tours, Inc. Iloilo Branch' => 'travel_ticketing2.php',
        'Southwest Tours - Iloilo Office' => 'travel_ticketing3.php',
        'EON TRAVEL & TOURS' => 'travel_ticketing4.php',
        'ELS TRAVEL & TOURS' => 'travel_ticketing5.php' , 

        // veterinary clinics
        'Tapales Veterinary Clinic' => 'veterinary1.php',
        'Jolly Vet Veterinary Clinic and Grooming Center' => 'veterinary2.php',
        'Petfurryville Veterinary Clinic' => 'veterinary3.php',
        'Family Vet' => 'veterinary4.php',
        'Dr. Paws Veterinary Clinic' => 'veterinary5.php',
        'Cornerstone Veterinary Clinic' => 'veterinary6.php',
        'Animal Care Clinic Veterinary Clinic and Grooming Center' => 'veterinary7.php',
        'Iloilo Veterinary Clinic' => 'veterinary8.php',
        'Demaisip Pet Doctors Veterinary Clinic' => 'veterinary9.php',
        'Ortega Petcare Veterinary Clinic' => 'veterinary10.php',
        'Pet Zone Veterinary Clinic' => 'veterinary11.php',
        'Happy Tails Veterinary Clinic' => 'veterinary12.php',
        'VetLine Animal Clinic' => 'veterinary13.php',
        'San Jose Veterinary Clinic' => 'veterinary14.php',
        'Paws and Claws Veterinary Clinic' => 'veterinary15.php',
        'Jaro Veterinary Clinic' => 'veterinary16.php',
        'Pet Wellness Veterinary Clinic' => 'veterinary17.php',
        'Dr. Dog Veterinary Clinic' => 'veterinary18.php',
        'Pet Haven Veterinary Clinic' => 'veterinary19.php',

        // water stations
        'Spintastic Water Refilling Station' => 'water_station1.php',
        'Aqua Luisa Purified Water Reffilling Station' => 'water_station2.php',
        'Aquatime Water Refilling Station' => 'water_station3.php',
        'Aqua Sure Water Station' => 'water_station4.php',
        'Nature\'s Spring Water Station' => 'water_station5.php',
        'Crystal Clear Water Station' => 'water_station6.php',

        // wellness spas
        'Mira Wellness Spa and Massage' => 'wellness_spa1.php',
        'I-HOMES - Iloilo Home of Massage and Essential Spa Company' => 'wellness_spa2.php',
        'Moana Day Spa Iloilo' => 'wellness_spa3.php',
        'Kyrain Wellness Spa' => 'wellness_spa4.php',
        'Kasanag Well-being Centre, Iloilo Main' => 'wellness_spa5.php',
        'Thai Royale Spa General Luna' => 'wellness_spa6.php',
        'Thai Royale Spa Jaro Iloilo Branch' => 'wellness_spa7.php',
        'Thai Royale Spa' => 'wellness_spa8.php',
        'Elle. Massage Therapy & Wellness Iloilo' => 'wellness_spa9.php',
        'Spa Olivenza - Jaro' => 'wellness_spa10.php',
        'Kasulhay Massage and Spa' => 'wellness_spa11.php',
        'Spa Riviera Prime Inc.' => 'wellness_spa12.php',
        'HOLA Massage & Spa' => 'wellness_spa13.php',
        'Spa Olivenza - General Luna' => 'wellness_spa14.php',
        'The Studio Spa' => 'wellness_spa15.php',
        'Thai Royale Spa Molo Iloilo Branch' => 'wellness_spa16.php',
        'Goldleaf SPA' => 'wellness_spa17.php',
        'SKINETICS WELLNESS CENTER' => 'wellness_spa18.php',
        '8th Street Spa' => 'wellness_spa19.php',
        'Atiyah Wellness & Spa Jaro' => 'wellness_spa20.php',
        'ATIYAH WELLNESS SPA MOLO' => 'wellness_spa21.php',
        'Senses Spa' => 'wellness_spa22.php',
        'GUGMA MASSAGE AND SPA' => 'wellness_spa23.php',
        'Zerenity Massage & Spa - Iloilo' => 'wellness_spa24.php',
        'Lemongrass Massage and Spa' => 'wellness_spa25.php',
        'Sparadise massage and spa' => 'wellness_spa26.php',
        'SPA-A-DAY' => 'wellness_spa27.php',
        'Cojian wellness spa' => 'wellness_spa28.php',
        'Asian Massage - Iloilo CIty' => 'wellness_spa29.php',
        'Kasanag Well-Being Centre' => 'wellness_spa30.php',
        'Hervansa Massage and Spa' => 'wellness_spa31.php',
        'Spa Olivenza - Mandurriao' => 'wellness_spa32.php',
        'Nuat Thai Foot & Body Massage' => 'wellness_spa33.php',


    ];

    foreach ($directMatches as $key => $file) {
        if (strtolower($key) === $query) {
            header("Location: $file");
            exit;
        }
    }

     $categoryKeywords = [
        'agency'        => 'agencies.php',
        'agencies'      => 'agencies.php',
        'agricultural store'  => 'agricultural_stores.php',
        'agricultural stores' => 'agricultural_stores.php',
        'livestock'     => 'agri_livestocks.php',
        'livestocks'    => 'agri_livestocks.php',
        'agrochemical supply'  => 'agrochemical_supplies.php',
        'agrochemical supplies'=> 'agrochemical_supplies.php',
        'announcement'  => 'announcements.php',
        'announcements' => 'announcements.php',
        'apartment'     => 'apartments.php',
        'apartments'    => 'apartments.php',
        'bakery'        => 'bakeries.php',
        'bakeries'      => 'bakeries.php',
        'bank'          => 'banks.php',
        'banks'         => 'banks.php',
        'barangay'      => 'barangays.php',
        'barangays'     => 'barangays.php',
        'barbershop'    => 'barbershops.php',
        'barbershops'   => 'barbershops.php',
        'bar'           => 'bars.php',
        'bars'          => 'bars.php',
        'bicycle shop'  => 'bicycle_shops.php',
        'bicycle shops' => 'bicycle_shops.php',
        'birth center'  => 'birth_centers.php',
        'birth centers' => 'birth_centers.php',
        'bus'           => 'bus.php',
        'cafe'          => 'cafes.php',
        'cafes'         => 'cafes.php',
        'call center'   => 'call_centers.php',
        'call centers'  => 'call_centers.php',
        'car dealership'=> 'car_dealerships.php',
        'car dealerships'=> 'car_dealerships.php',
        'car part'      => 'car_parts.php',
        'car parts'     => 'car_parts.php',
        'church'        => 'churches.php',
        'churches'      => 'churches.php',
        'clothing store'=> 'clothing_stores.php',
        'clothing stores'=> 'clothing_stores.php',
        'college'       => 'colleges.php',
        'colleges'      => 'colleges.php',
        'construction firm'=> 'construction_firms.php',
        'construction firms'=> 'construction_firms.php',
        'contact'       => 'contact_us.php',
        'contact us'    => 'contact_us.php',
        'convenience store'=> 'convenience_stores.php',
        'convenience stores'=> 'convenience_stores.php',
        'courier'       => 'couriers.php',
        'couriers'      => 'couriers.php',
        'cultural'      => 'culturals.php',
        'dental clinic' => 'dental_clinics.php',
        'dental clinics'=> 'dental_clinics.php',
        'dialysis center'=> 'dialysis_centers.php',
        'dialysis centers'=> 'dialysis_centers.php',
        'district'      => 'districts.php',
        'districts'     => 'districts.php',
        'drugstore'     => 'drugstores.php',
        'drugstores'    => 'drugstores.php',
        'elementary'    => 'elementarys.php',
        'elementarys'   => 'elementarys.php',
        'fast food'     => 'fast_foods.php',
        'fast foods'    => 'fast_foods.php',
        'ferry'         => 'ferries.php',
        'ferries'       => 'ferries.php',
        'festival'      => 'festivals.php',
        'festivals'     => 'festivals.php',
        'fire'          => 'fires.php',
        'fires'         => 'fires.php',
        'flower shop'   => 'flowershops.php',
        'flowershops'   => 'flowershops.php',
        'food'          => 'foods.php',
        'foods'         => 'foods.php',
        'funeral service'=> 'funeral_services.php',
        'funeral services'=> 'funeral_services.php',
        'gas station'   => 'gas_stations.php',
        'gas stations'  => 'gas_stations.php',
        'gym'           => 'gyms.php',
        'gyms'          => 'gyms.php',
        'hardware'      => 'hardware.php',
        'healthcare'    => 'healthcare.php',
        'school'        => 'highschools.php',
        'highschool'    => 'highschools.php',
        'high school'   => 'highschools.php',
        'highschools'   => 'highschools.php',
        'historical'    => 'historicals.php',
        'historicals'   => 'historicals.php',
        'home store'    => 'home_stores.php',
        'home stores'   => 'home_stores.php',
        'hospital'      => 'hospitals.php',
        'hospitals'     => 'hospitals.php',
        'hotel'         => 'hotels.php',
        'hotels'        => 'hotels.php',
        'internet service'=> 'internet_services.php',
        'internet services'=> 'internet_services.php',
        'jeep'          => 'jeeps.php',
        'jeeps'         => 'jeeps.php',
        'laundry service'=> 'laundry_services.php',
        'laundry services'=> 'laundry_services.php',
        'mall'          => 'malls.php',
        'malls'         => 'malls.php',
        'market'        => 'markets.php',
        'markets'       => 'markets.php',
        'meat shop'     => 'meat_shops.php',
        'meat shops'    => 'meat_shops.php',
        'medical diagnostic clinic' => 'medical_diagnostic_clinics.php',
        'medical diagnostic clinics' => 'medical_diagnostic_clinics.php',
        'motorcycle shop' => 'motorcycle_shops.php',
        'motorcycle shops' => 'motorcycle_shops.php',
        'new tourist spot' => 'new_tourist_spots.php',
        'new tourist spots' => 'new_tourist_spots.php',
        'optical clinic' => 'optical_clinics.php',
        'optical clinics' => 'optical_clinics.php',
        'pawnshop'      => 'pawnshops.php',
        'pawnshops'     => 'pawnshops.php',
        'pcg'           => 'pcg_details.php',
        'pcg details'   => 'pcg_details.php',
        'pharmacy'      => 'pharmacies.php',
        'pharmacies'    => 'pharmacies.php',
        'plaza'         => 'plaza.php',
        'police'        => 'pnps.php',
        'pnps'          => 'pnps.php',
        'printing service'=> 'printing_services.php',
        'printing services'=> 'printing_services.php',
        'resort'        => 'resorts.php',
        'resorts'       => 'resorts.php',
        'restaurant'    => 'restaurants.php',
        'restaurants'   => 'restaurants.php',
        'review center' => 'review_centers.php',
        'review centers'=> 'review_centers.php',
        'salon'         => 'salons.php',
        'salons'        => 'salons.php',
        'samgyupsal restaurant'=> 'samgyupsal_restaurants.php',
        'samgyupsal restaurants'=> 'samgyupsal_restaurants.php',
        'souvenir'      => 'souvenirs.php',
        'souvenirs'     => 'souvenirs.php',
        'street food'   => 'street_foods.php',
        'street foods'  => 'street_foods.php',
        'study hub'      => 'study_hubs.php',
        'study hubs'     => 'study_hubs.php',
        'terminal'      => 'terminals.php',
        'terminals'     => 'terminals.php',
        'transport'     => 'transportations.php',
        'transportation'=> 'transportations.php',
        'transportations'=> 'transportations.php',
        'travel agency' => 'travel_agencies.php',
        'travel agencies'=> 'travel_agencies.php',
        'travel ticketing'=> 'travel_ticketings.php',
        'travel ticketings'=> 'travel_ticketings.php',
        'veterinary clinic'=> 'veterinary_clinics.php',
        'veterinary clinics'=> 'veterinary_clinics.php',
        'water station' => 'water_stations.php',
        'water stations'=> 'water_stations.php',
        'wellness spa'  => 'wellness_spas.php',
        'wellness spas' => 'wellness_spas.php'


    ];

    foreach ($categoryKeywords as $keyword => $redirectPage) {
        if (strpos($query, $keyword) !== false) {
            header("Location: $redirectPage");
            exit;
        }
    }

    $tables = [
        'agencies' => 'agencies.php',
        'agricultural_stores' => 'agricultural_stores.php',
        'agri_livestocks' => 'agri_livestocks.php',
        'agrochemical_supplies' => 'agrochemical_supplies.php',
        'announcements' => 'announcements.php',
        'apartments' => 'apartments.php',
        'bakeries' => 'bakeries.php',
        'banks' => 'banks.php',
        'barangays' => 'barangays.php',
        'barbershops' => 'barbershops.php',
        'bars' => 'bars.php',
        'bicycle_shops' => 'bicycle_shops.php',
        'birth_centers' => 'birth_centers.php',
        'bus' => 'bus.php',
        'cafes' => 'cafes.php',
        'call_centers' => 'call_centers.php',
        'car_dealerships' => 'car_dealerships.php',
        'car_parts' => 'car_parts.php',
        'churches' => 'churches.php',
        'clothing_stores' => 'clothing_stores.php',
        'colleges' => 'colleges.php',
        'construction_firms' => 'construction_firms.php',
        'contact_us' => 'contact_us.php',
        'convenience_stores' => 'convenience_stores.php',
        'couriers' => 'couriers.php',
        'culturals' => 'culturals.php',
        'dental_clinics' => 'dental_clinics.php',
        'dialysis_centers' => 'dialysis_centers.php',
        'districts' => 'districts.php',
        'drugstores' => 'drugstores.php',
        'elementarys' => 'elementarys.php',
        'fast_foods' => 'fast_foods.php',
        'ferries' => 'ferries.php',
        'festivals' => 'festivals.php',
        'fires' => 'fires.php',
        'flowershops' => 'flowershops.php',
        'foods' => 'foods.php',
        'funeral_services' => 'funeral_services.php',
        'gas_stations' => 'gas_stations.php',
        'gyms' => 'gyms.php',
        'hardware' => 'hardware.php',
        'healthcare' => 'healthcare.php',
        'highschools' => 'highschools.php',
        'historicals' => 'historicals.php',
        'home_stores' => 'home_stores.php',
        'hospitals' => 'hospitals.php',
        'hotels' => 'hotels.php',
        'ilonggo_restaurants' => 'ilonggo_restaurants.php',
        'internet_services' => 'internet_services.php',
        'jeeps' => 'jeeps.php',
        'laundry_services' => 'laundry_services.php',
        'malls' => 'malls.php',
        'markets' => 'markets.php',
        'meat_shops' => 'meat_shops.php',
        'medical_diagnostic_clinics' => 'medical_diagnostic_clinics.php',
        'motorcycle_shops' => 'motorcycle_shops.php',
        'new_tourist_spots' => 'new_tourist_spots.php',
        'officials' => 'officials.php',
        'optical_clinics' => 'optical_clinics.php',
        'pawnshops' => 'pawnshops.php',
        'pcg_details' => 'pcg_details.php',
        'pharmacies' => 'pharmacies.php',
        'plaza' => 'plaza.php',
        'pnps' => 'pnps.php',
        'printing_services' => 'printing_services.php',
        'resorts' => 'resorts.php',
        'restaurants' => 'restaurants.php',
        'review centers'=> 'review_centers.php',
        'salons' => 'salons.php',
        'samgyupsal_restaurants' => 'samgyupsal_restaurants.php',
        'souvenirs' => 'souvenirs.php',
        'street_foods' => 'street_foods.php',
        'study_hubs'     => 'study_hubs.php',
        'terminals' => 'terminals.php',
        'transportations' => 'transportations.php',
        'travel_agencies' => 'travel_agencies.php',
        'travel_ticketings' => 'travel_ticketings.php',
        'veterinary_clinics' => 'veterinary_clinics.php',
        'water_stations' => 'water_stations.php',
        'wellness_spas' => 'wellness_spas.php',

    ];

    $results = [];
    

    foreach ($tables as $table => $redirectPage) {
        try {
            // Check if table exists and has a 'name' column
            $tableExists = $conn->query("SELECT 1 FROM `$table` LIMIT 1");
            if ($tableExists === false) continue;
            
            $check = $conn->query("SHOW COLUMNS FROM `$table` LIKE 'name'");
            if (!$check || $check->num_rows === 0) continue;

            // Search for matches in this table
            $stmt = $conn->prepare("SELECT * FROM `$table` WHERE LOWER(name) LIKE ?");
            $searchTerm = "%" . $query . "%";
            $stmt->bind_param("s", $searchTerm);
            $stmt->execute();
            $result = $stmt->get_result();
            
            while ($row = $result->fetch_assoc()) {
                // Check if this specific result has a direct match
                $directFile = null;
                foreach ($directMatches as $key => $file) {
                    if (strtolower($key) === strtolower($row['name'])) {
                        $directFile = $file;
                        break;
                    }
                }
                
                $results[] = [
                    'name' => $row['name'],
                    'description' => $row['description'] ?? '',
                    'table' => $table,
                    'redirect' => $directFile ? $directFile : $redirectPage,
                    'has_direct' => $directFile !== null
                ];
            }
            
            $stmt->close();
        } catch (mysqli_sql_exception $e) {
            // Skip tables that cause errors
            continue;
        }
    }

    // Step 4: Handle results
    if (count($results) === 1) {
        // If only one result, redirect directly to it
        header("Location: " . $results[0]['redirect']);
        exit;
    } elseif (!empty($results)) {
        // If multiple results, show results page
        $_SESSION['search_results'] = $results;
        $_SESSION['search_query'] = $query;
        header("Location: results.php");
        exit;
    } else {
        // No results found
        $_SESSION['search_results'] = [];
        $_SESSION['search_query'] = $query;
        header("Location: results.php");
        exit;
    }
} else {
    // If not a POST request, redirect to homepage
    header("Location: homepage.php");
    exit;
}

$conn->close();
?>